### PR TITLE
Refactor Webpack configs to allow emitting of robots.txt and sitemap.xml files.

### PR DESCRIPTION
**Pull request by nathandh**
Additional refactoring as follows:
    * Remove extra linting and standard js from package.json.
    * Custom linting setup and prettier were begin applied.
    * Also makes a correction so tests run with new linting setup.
    * Fixes broken navigation links.

### CODE REVIEW

**Comment by nathandh** [comment]
**Image showing tests running with custom linting**

Screenshot 2023-03-22 at 9 57 33 AM

**Comment by nathandh** [comment]
**Image showing SEO files being emitted from webpack**

Screenshot 2023-03-22 at 11 21 34 AM

**Comment by nathandh** [comment]
**Robots.txt file accessible on build**

Screenshot 2023-03-22 at 11 25 00 AM

**Comment by nathandh** [comment]
**Sitemap file accessible on build**

Screenshot 2023-03-22 at 11 24 49 AM

**Review by jnarlyv — APPROVED** [review]

**Review by dina-git — APPROVED** [review]

**Pull request merged**
