### PR TITLE
W3c validation and File Fixes

### PR DESCRIPTION
**Pull request by nathandh**

### CODE REVIEW

**Comment by nathandh** [comment]
Note: Also added ESLint, various configs, and linted the JS files in our package: https://github.com/nathandh/mywebclass-simulation/pull/50/commits/581cbaf2b9700752954c5f2638da986e4e3ca125

Several refactors were done to pass linting there.

**Comment by nathandh** [comment]
**JS refactored to resolve linting issues**

Screenshot 2023-03-21 at 1 11 21 AM

**Comment by nathandh** [comment]
**Various HTML files refactored to resolve Syntax issues**

Screenshot 2023-03-20 at 11 27 57 PM

**Comment by nathandh** [comment]
The errors in the preceding 2 screenshots will be resolved with this CR (Code Review).

**Review by jnarlyv — APPROVED** [review]

**Review by dina-git — APPROVED** [review]

**Pull request merged**
